#!/bin/bash
#SBATCH --time=14-00:00:00
#SBATCH --job-name=scrup.batch_20
#SBATCH --cpus-per-task=32
#SBATCH --mem=128G
#SBATCH --output=/home/sduan/data/scrup/logs/cellranger/batch_20.%j.log
#SBATCH --mail-type=BEGIN,END,FAIL
#SBATCH --mail-user=sduan@coh.org

/home/sduan/software/cellranger/9.0.1/bin/cellranger count --id=SRX8961819 --transcriptome=/home/sduan/reference_genomes/10xgenomics/GRCh38 --fastqs=/home/sduan/data/scrup/fastqs --sample=SRX8961819 --localcores=32 --localmem=128 --output-dir=/home/sduan/data/scrup/alignments/cellranger/SRX8961819 --create-bam true --nosecondary
/home/sduan/software/cellranger/9.0.1/bin/cellranger count --id=SRX8961820 --transcriptome=/home/sduan/reference_genomes/10xgenomics/GRCh38 --fastqs=/home/sduan/data/scrup/fastqs --sample=SRX8961820 --localcores=32 --localmem=128 --output-dir=/home/sduan/data/scrup/alignments/cellranger/SRX8961820 --create-bam true --nosecondary
/home/sduan/software/cellranger/9.0.1/bin/cellranger count --id=SRX8961821 --transcriptome=/home/sduan/reference_genomes/10xgenomics/GRCh38 --fastqs=/home/sduan/data/scrup/fastqs --sample=SRX8961821 --localcores=32 --localmem=128 --output-dir=/home/sduan/data/scrup/alignments/cellranger/SRX8961821 --create-bam true --nosecondary
/home/sduan/software/cellranger/9.0.1/bin/cellranger count --id=SRX8961822 --transcriptome=/home/sduan/reference_genomes/10xgenomics/GRCh38 --fastqs=/home/sduan/data/scrup/fastqs --sample=SRX8961822 --localcores=32 --localmem=128 --output-dir=/home/sduan/data/scrup/alignments/cellranger/SRX8961822 --create-bam true --nosecondary
/home/sduan/software/cellranger/9.0.1/bin/cellranger count --id=SRX8961823 --transcriptome=/home/sduan/reference_genomes/10xgenomics/GRCh38 --fastqs=/home/sduan/data/scrup/fastqs --sample=SRX8961823 --localcores=32 --localmem=128 --output-dir=/home/sduan/data/scrup/alignments/cellranger/SRX8961823 --create-bam true --nosecondary
/home/sduan/software/cellranger/9.0.1/bin/cellranger count --id=SRX8961824 --transcriptome=/home/sduan/reference_genomes/10xgenomics/GRCh38 --fastqs=/home/sduan/data/scrup/fastqs --sample=SRX8961824 --localcores=32 --localmem=128 --output-dir=/home/sduan/data/scrup/alignments/cellranger/SRX8961824 --create-bam true --nosecondary
/home/sduan/software/cellranger/9.0.1/bin/cellranger count --id=SRX8961825 --transcriptome=/home/sduan/reference_genomes/10xgenomics/GRCh38 --fastqs=/home/sduan/data/scrup/fastqs --sample=SRX8961825 --localcores=32 --localmem=128 --output-dir=/home/sduan/data/scrup/alignments/cellranger/SRX8961825 --create-bam true --nosecondary
/home/sduan/software/cellranger/9.0.1/bin/cellranger count --id=SRX8961826 --transcriptome=/home/sduan/reference_genomes/10xgenomics/GRCh38 --fastqs=/home/sduan/data/scrup/fastqs --sample=SRX8961826 --localcores=32 --localmem=128 --output-dir=/home/sduan/data/scrup/alignments/cellranger/SRX8961826 --create-bam true --nosecondary
/home/sduan/software/cellranger/9.0.1/bin/cellranger count --id=SRX8961827 --transcriptome=/home/sduan/reference_genomes/10xgenomics/GRCh38 --fastqs=/home/sduan/data/scrup/fastqs --sample=SRX8961827 --localcores=32 --localmem=128 --output-dir=/home/sduan/data/scrup/alignments/cellranger/SRX8961827 --create-bam true --nosecondary
/home/sduan/software/cellranger/9.0.1/bin/cellranger count --id=SRX8961828 --transcriptome=/home/sduan/reference_genomes/10xgenomics/GRCh38 --fastqs=/home/sduan/data/scrup/fastqs --sample=SRX8961828 --localcores=32 --localmem=128 --output-dir=/home/sduan/data/scrup/alignments/cellranger/SRX8961828 --create-bam true --nosecondary
/home/sduan/software/cellranger/9.0.1/bin/cellranger count --id=SRX8961829 --transcriptome=/home/sduan/reference_genomes/10xgenomics/GRCh38 --fastqs=/home/sduan/data/scrup/fastqs --sample=SRX8961829 --localcores=32 --localmem=128 --output-dir=/home/sduan/data/scrup/alignments/cellranger/SRX8961829 --create-bam true --nosecondary
/home/sduan/software/cellranger/9.0.1/bin/cellranger count --id=SRX8961830 --transcriptome=/home/sduan/reference_genomes/10xgenomics/GRCh38 --fastqs=/home/sduan/data/scrup/fastqs --sample=SRX8961830 --localcores=32 --localmem=128 --output-dir=/home/sduan/data/scrup/alignments/cellranger/SRX8961830 --create-bam true --nosecondary
/home/sduan/software/cellranger/9.0.1/bin/cellranger count --id=SRX8961831 --transcriptome=/home/sduan/reference_genomes/10xgenomics/GRCh38 --fastqs=/home/sduan/data/scrup/fastqs --sample=SRX8961831 --localcores=32 --localmem=128 --output-dir=/home/sduan/data/scrup/alignments/cellranger/SRX8961831 --create-bam true --nosecondary
/home/sduan/software/cellranger/9.0.1/bin/cellranger count --id=SRX8961832 --transcriptome=/home/sduan/reference_genomes/10xgenomics/GRCh38 --fastqs=/home/sduan/data/scrup/fastqs --sample=SRX8961832 --localcores=32 --localmem=128 --output-dir=/home/sduan/data/scrup/alignments/cellranger/SRX8961832 --create-bam true --nosecondary
/home/sduan/software/cellranger/9.0.1/bin/cellranger count --id=SRX8961833 --transcriptome=/home/sduan/reference_genomes/10xgenomics/GRCh38 --fastqs=/home/sduan/data/scrup/fastqs --sample=SRX8961833 --localcores=32 --localmem=128 --output-dir=/home/sduan/data/scrup/alignments/cellranger/SRX8961833 --create-bam true --nosecondary
/home/sduan/software/cellranger/9.0.1/bin/cellranger count --id=SRX9172129 --transcriptome=/home/sduan/reference_genomes/10xgenomics/GRCh38 --fastqs=/home/sduan/data/scrup/fastqs --sample=SRX9172129 --localcores=32 --localmem=128 --output-dir=/home/sduan/data/scrup/alignments/cellranger/SRX9172129 --create-bam true --nosecondary
/home/sduan/software/cellranger/9.0.1/bin/cellranger count --id=SRX9172130 --transcriptome=/home/sduan/reference_genomes/10xgenomics/GRCh38 --fastqs=/home/sduan/data/scrup/fastqs --sample=SRX9172130 --localcores=32 --localmem=128 --output-dir=/home/sduan/data/scrup/alignments/cellranger/SRX9172130 --create-bam true --nosecondary
/home/sduan/software/cellranger/9.0.1/bin/cellranger count --id=SRX9172131 --transcriptome=/home/sduan/reference_genomes/10xgenomics/GRCh38 --fastqs=/home/sduan/data/scrup/fastqs --sample=SRX9172131 --localcores=32 --localmem=128 --output-dir=/home/sduan/data/scrup/alignments/cellranger/SRX9172131 --create-bam true --nosecondary
/home/sduan/software/cellranger/9.0.1/bin/cellranger count --id=SRX9172132 --transcriptome=/home/sduan/reference_genomes/10xgenomics/GRCh38 --fastqs=/home/sduan/data/scrup/fastqs --sample=SRX9172132 --localcores=32 --localmem=128 --output-dir=/home/sduan/data/scrup/alignments/cellranger/SRX9172132 --create-bam true --nosecondary
/home/sduan/software/cellranger/9.0.1/bin/cellranger count --id=SRX9172133 --transcriptome=/home/sduan/reference_genomes/10xgenomics/GRCh38 --fastqs=/home/sduan/data/scrup/fastqs --sample=SRX9172133 --localcores=32 --localmem=128 --output-dir=/home/sduan/data/scrup/alignments/cellranger/SRX9172133 --create-bam true --nosecondary
/home/sduan/software/cellranger/9.0.1/bin/cellranger count --id=SRX9172134 --transcriptome=/home/sduan/reference_genomes/10xgenomics/GRCh38 --fastqs=/home/sduan/data/scrup/fastqs --sample=SRX9172134 --localcores=32 --localmem=128 --output-dir=/home/sduan/data/scrup/alignments/cellranger/SRX9172134 --create-bam true --nosecondary
/home/sduan/software/cellranger/9.0.1/bin/cellranger count --id=SRX9172135 --transcriptome=/home/sduan/reference_genomes/10xgenomics/GRCh38 --fastqs=/home/sduan/data/scrup/fastqs --sample=SRX9172135 --localcores=32 --localmem=128 --output-dir=/home/sduan/data/scrup/alignments/cellranger/SRX9172135 --create-bam true --nosecondary
/home/sduan/software/cellranger/9.0.1/bin/cellranger count --id=SRX9172136 --transcriptome=/home/sduan/reference_genomes/10xgenomics/GRCh38 --fastqs=/home/sduan/data/scrup/fastqs --sample=SRX9172136 --localcores=32 --localmem=128 --output-dir=/home/sduan/data/scrup/alignments/cellranger/SRX9172136 --create-bam true --nosecondary
/home/sduan/software/cellranger/9.0.1/bin/cellranger count --id=SRX9172137 --transcriptome=/home/sduan/reference_genomes/10xgenomics/GRCh38 --fastqs=/home/sduan/data/scrup/fastqs --sample=SRX9172137 --localcores=32 --localmem=128 --output-dir=/home/sduan/data/scrup/alignments/cellranger/SRX9172137 --create-bam true --nosecondary
/home/sduan/software/cellranger/9.0.1/bin/cellranger count --id=SRX9207566 --transcriptome=/home/sduan/reference_genomes/10xgenomics/GRCh38 --fastqs=/home/sduan/data/scrup/fastqs --sample=SRX9207566 --localcores=32 --localmem=128 --output-dir=/home/sduan/data/scrup/alignments/cellranger/SRX9207566 --create-bam true --nosecondary
/home/sduan/software/cellranger/9.0.1/bin/cellranger count --id=SRX9207567 --transcriptome=/home/sduan/reference_genomes/10xgenomics/GRCh38 --fastqs=/home/sduan/data/scrup/fastqs --sample=SRX9207567 --localcores=32 --localmem=128 --output-dir=/home/sduan/data/scrup/alignments/cellranger/SRX9207567 --create-bam true --nosecondary
/home/sduan/software/cellranger/9.0.1/bin/cellranger count --id=SRX9207568 --transcriptome=/home/sduan/reference_genomes/10xgenomics/GRCh38 --fastqs=/home/sduan/data/scrup/fastqs --sample=SRX9207568 --localcores=32 --localmem=128 --output-dir=/home/sduan/data/scrup/alignments/cellranger/SRX9207568 --create-bam true --nosecondary
/home/sduan/software/cellranger/9.0.1/bin/cellranger count --id=SRX9207569 --transcriptome=/home/sduan/reference_genomes/10xgenomics/GRCh38 --fastqs=/home/sduan/data/scrup/fastqs --sample=SRX9207569 --localcores=32 --localmem=128 --output-dir=/home/sduan/data/scrup/alignments/cellranger/SRX9207569 --create-bam true --nosecondary
/home/sduan/software/cellranger/9.0.1/bin/cellranger count --id=SRX9207570 --transcriptome=/home/sduan/reference_genomes/10xgenomics/GRCh38 --fastqs=/home/sduan/data/scrup/fastqs --sample=SRX9207570 --localcores=32 --localmem=128 --output-dir=/home/sduan/data/scrup/alignments/cellranger/SRX9207570 --create-bam true --nosecondary
/home/sduan/software/cellranger/9.0.1/bin/cellranger count --id=SRX9207571 --transcriptome=/home/sduan/reference_genomes/10xgenomics/GRCh38 --fastqs=/home/sduan/data/scrup/fastqs --sample=SRX9207571 --localcores=32 --localmem=128 --output-dir=/home/sduan/data/scrup/alignments/cellranger/SRX9207571 --create-bam true --nosecondary
/home/sduan/software/cellranger/9.0.1/bin/cellranger count --id=SRX9207572 --transcriptome=/home/sduan/reference_genomes/10xgenomics/GRCh38 --fastqs=/home/sduan/data/scrup/fastqs --sample=SRX9207572 --localcores=32 --localmem=128 --output-dir=/home/sduan/data/scrup/alignments/cellranger/SRX9207572 --create-bam true --nosecondary
/home/sduan/software/cellranger/9.0.1/bin/cellranger count --id=SRX9207573 --transcriptome=/home/sduan/reference_genomes/10xgenomics/GRCh38 --fastqs=/home/sduan/data/scrup/fastqs --sample=SRX9207573 --localcores=32 --localmem=128 --output-dir=/home/sduan/data/scrup/alignments/cellranger/SRX9207573 --create-bam true --nosecondary
/home/sduan/software/cellranger/9.0.1/bin/cellranger count --id=SRX9207574 --transcriptome=/home/sduan/reference_genomes/10xgenomics/GRCh38 --fastqs=/home/sduan/data/scrup/fastqs --sample=SRX9207574 --localcores=32 --localmem=128 --output-dir=/home/sduan/data/scrup/alignments/cellranger/SRX9207574 --create-bam true --nosecondary
/home/sduan/software/cellranger/9.0.1/bin/cellranger count --id=SRX9207575 --transcriptome=/home/sduan/reference_genomes/10xgenomics/GRCh38 --fastqs=/home/sduan/data/scrup/fastqs --sample=SRX9207575 --localcores=32 --localmem=128 --output-dir=/home/sduan/data/scrup/alignments/cellranger/SRX9207575 --create-bam true --nosecondary
/home/sduan/software/cellranger/9.0.1/bin/cellranger count --id=SRX9207576 --transcriptome=/home/sduan/reference_genomes/10xgenomics/GRCh38 --fastqs=/home/sduan/data/scrup/fastqs --sample=SRX9207576 --localcores=32 --localmem=128 --output-dir=/home/sduan/data/scrup/alignments/cellranger/SRX9207576 --create-bam true --nosecondary
/home/sduan/software/cellranger/9.0.1/bin/cellranger count --id=SRX9207577 --transcriptome=/home/sduan/reference_genomes/10xgenomics/GRCh38 --fastqs=/home/sduan/data/scrup/fastqs --sample=SRX9207577 --localcores=32 --localmem=128 --output-dir=/home/sduan/data/scrup/alignments/cellranger/SRX9207577 --create-bam true --nosecondary
/home/sduan/software/cellranger/9.0.1/bin/cellranger count --id=SRX9207578 --transcriptome=/home/sduan/reference_genomes/10xgenomics/GRCh38 --fastqs=/home/sduan/data/scrup/fastqs --sample=SRX9207578 --localcores=32 --localmem=128 --output-dir=/home/sduan/data/scrup/alignments/cellranger/SRX9207578 --create-bam true --nosecondary
/home/sduan/software/cellranger/9.0.1/bin/cellranger count --id=SRX9219158 --transcriptome=/home/sduan/reference_genomes/10xgenomics/GRCh38 --fastqs=/home/sduan/data/scrup/fastqs --sample=SRX9219158 --localcores=32 --localmem=128 --output-dir=/home/sduan/data/scrup/alignments/cellranger/SRX9219158 --create-bam true --nosecondary
/home/sduan/software/cellranger/9.0.1/bin/cellranger count --id=SRX9219159 --transcriptome=/home/sduan/reference_genomes/10xgenomics/GRCh38 --fastqs=/home/sduan/data/scrup/fastqs --sample=SRX9219159 --localcores=32 --localmem=128 --output-dir=/home/sduan/data/scrup/alignments/cellranger/SRX9219159 --create-bam true --nosecondary
/home/sduan/software/cellranger/9.0.1/bin/cellranger count --id=SRX9219160 --transcriptome=/home/sduan/reference_genomes/10xgenomics/GRCh38 --fastqs=/home/sduan/data/scrup/fastqs --sample=SRX9219160 --localcores=32 --localmem=128 --output-dir=/home/sduan/data/scrup/alignments/cellranger/SRX9219160 --create-bam true --nosecondary
/home/sduan/software/cellranger/9.0.1/bin/cellranger count --id=SRX9219161 --transcriptome=/home/sduan/reference_genomes/10xgenomics/GRCh38 --fastqs=/home/sduan/data/scrup/fastqs --sample=SRX9219161 --localcores=32 --localmem=128 --output-dir=/home/sduan/data/scrup/alignments/cellranger/SRX9219161 --create-bam true --nosecondary
/home/sduan/software/cellranger/9.0.1/bin/cellranger count --id=SRX9219162 --transcriptome=/home/sduan/reference_genomes/10xgenomics/GRCh38 --fastqs=/home/sduan/data/scrup/fastqs --sample=SRX9219162 --localcores=32 --localmem=128 --output-dir=/home/sduan/data/scrup/alignments/cellranger/SRX9219162 --create-bam true --nosecondary
/home/sduan/software/cellranger/9.0.1/bin/cellranger count --id=SRX9219163 --transcriptome=/home/sduan/reference_genomes/10xgenomics/GRCh38 --fastqs=/home/sduan/data/scrup/fastqs --sample=SRX9219163 --localcores=32 --localmem=128 --output-dir=/home/sduan/data/scrup/alignments/cellranger/SRX9219163 --create-bam true --nosecondary
/home/sduan/software/cellranger/9.0.1/bin/cellranger count --id=SRX9219164 --transcriptome=/home/sduan/reference_genomes/10xgenomics/GRCh38 --fastqs=/home/sduan/data/scrup/fastqs --sample=SRX9219164 --localcores=32 --localmem=128 --output-dir=/home/sduan/data/scrup/alignments/cellranger/SRX9219164 --create-bam true --nosecondary
/home/sduan/software/cellranger/9.0.1/bin/cellranger count --id=SRX9219165 --transcriptome=/home/sduan/reference_genomes/10xgenomics/GRCh38 --fastqs=/home/sduan/data/scrup/fastqs --sample=SRX9219165 --localcores=32 --localmem=128 --output-dir=/home/sduan/data/scrup/alignments/cellranger/SRX9219165 --create-bam true --nosecondary
/home/sduan/software/cellranger/9.0.1/bin/cellranger count --id=SRX9219166 --transcriptome=/home/sduan/reference_genomes/10xgenomics/GRCh38 --fastqs=/home/sduan/data/scrup/fastqs --sample=SRX9219166 --localcores=32 --localmem=128 --output-dir=/home/sduan/data/scrup/alignments/cellranger/SRX9219166 --create-bam true --nosecondary
/home/sduan/software/cellranger/9.0.1/bin/cellranger count --id=SRX9219167 --transcriptome=/home/sduan/reference_genomes/10xgenomics/GRCh38 --fastqs=/home/sduan/data/scrup/fastqs --sample=SRX9219167 --localcores=32 --localmem=128 --output-dir=/home/sduan/data/scrup/alignments/cellranger/SRX9219167 --create-bam true --nosecondary
/home/sduan/software/cellranger/9.0.1/bin/cellranger count --id=SRX9808466 --transcriptome=/home/sduan/reference_genomes/10xgenomics/GRCh38 --fastqs=/home/sduan/data/scrup/fastqs --sample=SRX9808466 --localcores=32 --localmem=128 --output-dir=/home/sduan/data/scrup/alignments/cellranger/SRX9808466 --create-bam true --nosecondary
/home/sduan/software/cellranger/9.0.1/bin/cellranger count --id=SRX9808467 --transcriptome=/home/sduan/reference_genomes/10xgenomics/GRCh38 --fastqs=/home/sduan/data/scrup/fastqs --sample=SRX9808467 --localcores=32 --localmem=128 --output-dir=/home/sduan/data/scrup/alignments/cellranger/SRX9808467 --create-bam true --nosecondary
/home/sduan/software/cellranger/9.0.1/bin/cellranger count --id=SRX9808468 --transcriptome=/home/sduan/reference_genomes/10xgenomics/GRCh38 --fastqs=/home/sduan/data/scrup/fastqs --sample=SRX9808468 --localcores=32 --localmem=128 --output-dir=/home/sduan/data/scrup/alignments/cellranger/SRX9808468 --create-bam true --nosecondary
/home/sduan/software/cellranger/9.0.1/bin/cellranger count --id=SRX9808469 --transcriptome=/home/sduan/reference_genomes/10xgenomics/GRCh38 --fastqs=/home/sduan/data/scrup/fastqs --sample=SRX9808469 --localcores=32 --localmem=128 --output-dir=/home/sduan/data/scrup/alignments/cellranger/SRX9808469 --create-bam true --nosecondary
/home/sduan/software/cellranger/9.0.1/bin/cellranger count --id=SRX9808470 --transcriptome=/home/sduan/reference_genomes/10xgenomics/GRCh38 --fastqs=/home/sduan/data/scrup/fastqs --sample=SRX9808470 --localcores=32 --localmem=128 --output-dir=/home/sduan/data/scrup/alignments/cellranger/SRX9808470 --create-bam true --nosecondary
/home/sduan/software/cellranger/9.0.1/bin/cellranger count --id=SRX9808471 --transcriptome=/home/sduan/reference_genomes/10xgenomics/GRCh38 --fastqs=/home/sduan/data/scrup/fastqs --sample=SRX9808471 --localcores=32 --localmem=128 --output-dir=/home/sduan/data/scrup/alignments/cellranger/SRX9808471 --create-bam true --nosecondary
