#!/bin/bash
#SBATCH --time=14-00:00:00
#SBATCH --job-name=scrup.batch_19
#SBATCH --cpus-per-task=32
#SBATCH --mem=128G
#SBATCH --output=/home/sduan/data/scrup/logs/cellranger/batch_19.%j.log
#SBATCH --mail-type=BEGIN,END,FAIL
#SBATCH --mail-user=sduan@coh.org

/home/sduan/software/cellranger/9.0.1/bin/cellranger count --id=SRX5137779 --transcriptome=/home/sduan/reference_genomes/10xgenomics/GRCh38 --fastqs=/home/sduan/data/scrup/fastqs --sample=SRX5137779 --localcores=32 --localmem=128 --output-dir=/home/sduan/data/scrup/alignments/cellranger/SRX5137779 --create-bam true --nosecondary
/home/sduan/software/cellranger/9.0.1/bin/cellranger count --id=SRX5137780 --transcriptome=/home/sduan/reference_genomes/10xgenomics/GRCh38 --fastqs=/home/sduan/data/scrup/fastqs --sample=SRX5137780 --localcores=32 --localmem=128 --output-dir=/home/sduan/data/scrup/alignments/cellranger/SRX5137780 --create-bam true --nosecondary
/home/sduan/software/cellranger/9.0.1/bin/cellranger count --id=SRX6471037 --transcriptome=/home/sduan/reference_genomes/10xgenomics/GRCh38 --fastqs=/home/sduan/data/scrup/fastqs --sample=SRX6471037 --localcores=32 --localmem=128 --output-dir=/home/sduan/data/scrup/alignments/cellranger/SRX6471037 --create-bam true --nosecondary
/home/sduan/software/cellranger/9.0.1/bin/cellranger count --id=SRX6881705 --transcriptome=/home/sduan/reference_genomes/10xgenomics/GRCh38 --fastqs=/home/sduan/data/scrup/fastqs --sample=SRX6881705 --localcores=32 --localmem=128 --output-dir=/home/sduan/data/scrup/alignments/cellranger/SRX6881705 --create-bam true --nosecondary
/home/sduan/software/cellranger/9.0.1/bin/cellranger count --id=SRX6881706 --transcriptome=/home/sduan/reference_genomes/10xgenomics/GRCh38 --fastqs=/home/sduan/data/scrup/fastqs --sample=SRX6881706 --localcores=32 --localmem=128 --output-dir=/home/sduan/data/scrup/alignments/cellranger/SRX6881706 --create-bam true --nosecondary
/home/sduan/software/cellranger/9.0.1/bin/cellranger count --id=SRX6881707 --transcriptome=/home/sduan/reference_genomes/10xgenomics/GRCh38 --fastqs=/home/sduan/data/scrup/fastqs --sample=SRX6881707 --localcores=32 --localmem=128 --output-dir=/home/sduan/data/scrup/alignments/cellranger/SRX6881707 --create-bam true --nosecondary
/home/sduan/software/cellranger/9.0.1/bin/cellranger count --id=SRX6881708 --transcriptome=/home/sduan/reference_genomes/10xgenomics/GRCh38 --fastqs=/home/sduan/data/scrup/fastqs --sample=SRX6881708 --localcores=32 --localmem=128 --output-dir=/home/sduan/data/scrup/alignments/cellranger/SRX6881708 --create-bam true --nosecondary
/home/sduan/software/cellranger/9.0.1/bin/cellranger count --id=SRX6881709 --transcriptome=/home/sduan/reference_genomes/10xgenomics/GRCh38 --fastqs=/home/sduan/data/scrup/fastqs --sample=SRX6881709 --localcores=32 --localmem=128 --output-dir=/home/sduan/data/scrup/alignments/cellranger/SRX6881709 --create-bam true --nosecondary
/home/sduan/software/cellranger/9.0.1/bin/cellranger count --id=SRX6881710 --transcriptome=/home/sduan/reference_genomes/10xgenomics/GRCh38 --fastqs=/home/sduan/data/scrup/fastqs --sample=SRX6881710 --localcores=32 --localmem=128 --output-dir=/home/sduan/data/scrup/alignments/cellranger/SRX6881710 --create-bam true --nosecondary
/home/sduan/software/cellranger/9.0.1/bin/cellranger count --id=SRX6881711 --transcriptome=/home/sduan/reference_genomes/10xgenomics/GRCh38 --fastqs=/home/sduan/data/scrup/fastqs --sample=SRX6881711 --localcores=32 --localmem=128 --output-dir=/home/sduan/data/scrup/alignments/cellranger/SRX6881711 --create-bam true --nosecondary
/home/sduan/software/cellranger/9.0.1/bin/cellranger count --id=SRX6881712 --transcriptome=/home/sduan/reference_genomes/10xgenomics/GRCh38 --fastqs=/home/sduan/data/scrup/fastqs --sample=SRX6881712 --localcores=32 --localmem=128 --output-dir=/home/sduan/data/scrup/alignments/cellranger/SRX6881712 --create-bam true --nosecondary
/home/sduan/software/cellranger/9.0.1/bin/cellranger count --id=SRX6881713 --transcriptome=/home/sduan/reference_genomes/10xgenomics/GRCh38 --fastqs=/home/sduan/data/scrup/fastqs --sample=SRX6881713 --localcores=32 --localmem=128 --output-dir=/home/sduan/data/scrup/alignments/cellranger/SRX6881713 --create-bam true --nosecondary
/home/sduan/software/cellranger/9.0.1/bin/cellranger count --id=SRX6881714 --transcriptome=/home/sduan/reference_genomes/10xgenomics/GRCh38 --fastqs=/home/sduan/data/scrup/fastqs --sample=SRX6881714 --localcores=32 --localmem=128 --output-dir=/home/sduan/data/scrup/alignments/cellranger/SRX6881714 --create-bam true --nosecondary
/home/sduan/software/cellranger/9.0.1/bin/cellranger count --id=SRX6881716 --transcriptome=/home/sduan/reference_genomes/10xgenomics/GRCh38 --fastqs=/home/sduan/data/scrup/fastqs --sample=SRX6881716 --localcores=32 --localmem=128 --output-dir=/home/sduan/data/scrup/alignments/cellranger/SRX6881716 --create-bam true --nosecondary
/home/sduan/software/cellranger/9.0.1/bin/cellranger count --id=SRX6881717 --transcriptome=/home/sduan/reference_genomes/10xgenomics/GRCh38 --fastqs=/home/sduan/data/scrup/fastqs --sample=SRX6881717 --localcores=32 --localmem=128 --output-dir=/home/sduan/data/scrup/alignments/cellranger/SRX6881717 --create-bam true --nosecondary
/home/sduan/software/cellranger/9.0.1/bin/cellranger count --id=SRX6881718 --transcriptome=/home/sduan/reference_genomes/10xgenomics/GRCh38 --fastqs=/home/sduan/data/scrup/fastqs --sample=SRX6881718 --localcores=32 --localmem=128 --output-dir=/home/sduan/data/scrup/alignments/cellranger/SRX6881718 --create-bam true --nosecondary
/home/sduan/software/cellranger/9.0.1/bin/cellranger count --id=SRX6881719 --transcriptome=/home/sduan/reference_genomes/10xgenomics/GRCh38 --fastqs=/home/sduan/data/scrup/fastqs --sample=SRX6881719 --localcores=32 --localmem=128 --output-dir=/home/sduan/data/scrup/alignments/cellranger/SRX6881719 --create-bam true --nosecondary
/home/sduan/software/cellranger/9.0.1/bin/cellranger count --id=SRX7063666 --transcriptome=/home/sduan/reference_genomes/10xgenomics/GRCh38 --fastqs=/home/sduan/data/scrup/fastqs --sample=SRX7063666 --localcores=32 --localmem=128 --output-dir=/home/sduan/data/scrup/alignments/cellranger/SRX7063666 --create-bam true --nosecondary
/home/sduan/software/cellranger/9.0.1/bin/cellranger count --id=SRX7063667 --transcriptome=/home/sduan/reference_genomes/10xgenomics/GRCh38 --fastqs=/home/sduan/data/scrup/fastqs --sample=SRX7063667 --localcores=32 --localmem=128 --output-dir=/home/sduan/data/scrup/alignments/cellranger/SRX7063667 --create-bam true --nosecondary
/home/sduan/software/cellranger/9.0.1/bin/cellranger count --id=SRX7063668 --transcriptome=/home/sduan/reference_genomes/10xgenomics/GRCh38 --fastqs=/home/sduan/data/scrup/fastqs --sample=SRX7063668 --localcores=32 --localmem=128 --output-dir=/home/sduan/data/scrup/alignments/cellranger/SRX7063668 --create-bam true --nosecondary
/home/sduan/software/cellranger/9.0.1/bin/cellranger count --id=SRX7539347 --transcriptome=/home/sduan/reference_genomes/10xgenomics/GRCh38 --fastqs=/home/sduan/data/scrup/fastqs --sample=SRX7539347 --localcores=32 --localmem=128 --output-dir=/home/sduan/data/scrup/alignments/cellranger/SRX7539347 --create-bam true --nosecondary
/home/sduan/software/cellranger/9.0.1/bin/cellranger count --id=SRX7539348 --transcriptome=/home/sduan/reference_genomes/10xgenomics/GRCh38 --fastqs=/home/sduan/data/scrup/fastqs --sample=SRX7539348 --localcores=32 --localmem=128 --output-dir=/home/sduan/data/scrup/alignments/cellranger/SRX7539348 --create-bam true --nosecondary
/home/sduan/software/cellranger/9.0.1/bin/cellranger count --id=SRX7539349 --transcriptome=/home/sduan/reference_genomes/10xgenomics/GRCh38 --fastqs=/home/sduan/data/scrup/fastqs --sample=SRX7539349 --localcores=32 --localmem=128 --output-dir=/home/sduan/data/scrup/alignments/cellranger/SRX7539349 --create-bam true --nosecondary
/home/sduan/software/cellranger/9.0.1/bin/cellranger count --id=SRX7539350 --transcriptome=/home/sduan/reference_genomes/10xgenomics/GRCh38 --fastqs=/home/sduan/data/scrup/fastqs --sample=SRX7539350 --localcores=32 --localmem=128 --output-dir=/home/sduan/data/scrup/alignments/cellranger/SRX7539350 --create-bam true --nosecondary
/home/sduan/software/cellranger/9.0.1/bin/cellranger count --id=SRX8668244 --transcriptome=/home/sduan/reference_genomes/10xgenomics/GRCh38 --fastqs=/home/sduan/data/scrup/fastqs --sample=SRX8668244 --localcores=32 --localmem=128 --output-dir=/home/sduan/data/scrup/alignments/cellranger/SRX8668244 --create-bam true --nosecondary
/home/sduan/software/cellranger/9.0.1/bin/cellranger count --id=SRX8668245 --transcriptome=/home/sduan/reference_genomes/10xgenomics/GRCh38 --fastqs=/home/sduan/data/scrup/fastqs --sample=SRX8668245 --localcores=32 --localmem=128 --output-dir=/home/sduan/data/scrup/alignments/cellranger/SRX8668245 --create-bam true --nosecondary
/home/sduan/software/cellranger/9.0.1/bin/cellranger count --id=SRX8668246 --transcriptome=/home/sduan/reference_genomes/10xgenomics/GRCh38 --fastqs=/home/sduan/data/scrup/fastqs --sample=SRX8668246 --localcores=32 --localmem=128 --output-dir=/home/sduan/data/scrup/alignments/cellranger/SRX8668246 --create-bam true --nosecondary
/home/sduan/software/cellranger/9.0.1/bin/cellranger count --id=SRX8668247 --transcriptome=/home/sduan/reference_genomes/10xgenomics/GRCh38 --fastqs=/home/sduan/data/scrup/fastqs --sample=SRX8668247 --localcores=32 --localmem=128 --output-dir=/home/sduan/data/scrup/alignments/cellranger/SRX8668247 --create-bam true --nosecondary
/home/sduan/software/cellranger/9.0.1/bin/cellranger count --id=SRX8668248 --transcriptome=/home/sduan/reference_genomes/10xgenomics/GRCh38 --fastqs=/home/sduan/data/scrup/fastqs --sample=SRX8668248 --localcores=32 --localmem=128 --output-dir=/home/sduan/data/scrup/alignments/cellranger/SRX8668248 --create-bam true --nosecondary
/home/sduan/software/cellranger/9.0.1/bin/cellranger count --id=SRX8668249 --transcriptome=/home/sduan/reference_genomes/10xgenomics/GRCh38 --fastqs=/home/sduan/data/scrup/fastqs --sample=SRX8668249 --localcores=32 --localmem=128 --output-dir=/home/sduan/data/scrup/alignments/cellranger/SRX8668249 --create-bam true --nosecondary
/home/sduan/software/cellranger/9.0.1/bin/cellranger count --id=SRX8668250 --transcriptome=/home/sduan/reference_genomes/10xgenomics/GRCh38 --fastqs=/home/sduan/data/scrup/fastqs --sample=SRX8668250 --localcores=32 --localmem=128 --output-dir=/home/sduan/data/scrup/alignments/cellranger/SRX8668250 --create-bam true --nosecondary
/home/sduan/software/cellranger/9.0.1/bin/cellranger count --id=SRX8668251 --transcriptome=/home/sduan/reference_genomes/10xgenomics/GRCh38 --fastqs=/home/sduan/data/scrup/fastqs --sample=SRX8668251 --localcores=32 --localmem=128 --output-dir=/home/sduan/data/scrup/alignments/cellranger/SRX8668251 --create-bam true --nosecondary
/home/sduan/software/cellranger/9.0.1/bin/cellranger count --id=SRX8778045 --transcriptome=/home/sduan/reference_genomes/10xgenomics/GRCh38 --fastqs=/home/sduan/data/scrup/fastqs --sample=SRX8778045 --localcores=32 --localmem=128 --output-dir=/home/sduan/data/scrup/alignments/cellranger/SRX8778045 --create-bam true --nosecondary
/home/sduan/software/cellranger/9.0.1/bin/cellranger count --id=SRX8778046 --transcriptome=/home/sduan/reference_genomes/10xgenomics/GRCh38 --fastqs=/home/sduan/data/scrup/fastqs --sample=SRX8778046 --localcores=32 --localmem=128 --output-dir=/home/sduan/data/scrup/alignments/cellranger/SRX8778046 --create-bam true --nosecondary
/home/sduan/software/cellranger/9.0.1/bin/cellranger count --id=SRX8778047 --transcriptome=/home/sduan/reference_genomes/10xgenomics/GRCh38 --fastqs=/home/sduan/data/scrup/fastqs --sample=SRX8778047 --localcores=32 --localmem=128 --output-dir=/home/sduan/data/scrup/alignments/cellranger/SRX8778047 --create-bam true --nosecondary
/home/sduan/software/cellranger/9.0.1/bin/cellranger count --id=SRX8778048 --transcriptome=/home/sduan/reference_genomes/10xgenomics/GRCh38 --fastqs=/home/sduan/data/scrup/fastqs --sample=SRX8778048 --localcores=32 --localmem=128 --output-dir=/home/sduan/data/scrup/alignments/cellranger/SRX8778048 --create-bam true --nosecondary
/home/sduan/software/cellranger/9.0.1/bin/cellranger count --id=SRX8778049 --transcriptome=/home/sduan/reference_genomes/10xgenomics/GRCh38 --fastqs=/home/sduan/data/scrup/fastqs --sample=SRX8778049 --localcores=32 --localmem=128 --output-dir=/home/sduan/data/scrup/alignments/cellranger/SRX8778049 --create-bam true --nosecondary
/home/sduan/software/cellranger/9.0.1/bin/cellranger count --id=SRX8778050 --transcriptome=/home/sduan/reference_genomes/10xgenomics/GRCh38 --fastqs=/home/sduan/data/scrup/fastqs --sample=SRX8778050 --localcores=32 --localmem=128 --output-dir=/home/sduan/data/scrup/alignments/cellranger/SRX8778050 --create-bam true --nosecondary
/home/sduan/software/cellranger/9.0.1/bin/cellranger count --id=SRX8778051 --transcriptome=/home/sduan/reference_genomes/10xgenomics/GRCh38 --fastqs=/home/sduan/data/scrup/fastqs --sample=SRX8778051 --localcores=32 --localmem=128 --output-dir=/home/sduan/data/scrup/alignments/cellranger/SRX8778051 --create-bam true --nosecondary
/home/sduan/software/cellranger/9.0.1/bin/cellranger count --id=SRX8778052 --transcriptome=/home/sduan/reference_genomes/10xgenomics/GRCh38 --fastqs=/home/sduan/data/scrup/fastqs --sample=SRX8778052 --localcores=32 --localmem=128 --output-dir=/home/sduan/data/scrup/alignments/cellranger/SRX8778052 --create-bam true --nosecondary
/home/sduan/software/cellranger/9.0.1/bin/cellranger count --id=SRX8778053 --transcriptome=/home/sduan/reference_genomes/10xgenomics/GRCh38 --fastqs=/home/sduan/data/scrup/fastqs --sample=SRX8778053 --localcores=32 --localmem=128 --output-dir=/home/sduan/data/scrup/alignments/cellranger/SRX8778053 --create-bam true --nosecondary
/home/sduan/software/cellranger/9.0.1/bin/cellranger count --id=SRX8778054 --transcriptome=/home/sduan/reference_genomes/10xgenomics/GRCh38 --fastqs=/home/sduan/data/scrup/fastqs --sample=SRX8778054 --localcores=32 --localmem=128 --output-dir=/home/sduan/data/scrup/alignments/cellranger/SRX8778054 --create-bam true --nosecondary
/home/sduan/software/cellranger/9.0.1/bin/cellranger count --id=SRX8778055 --transcriptome=/home/sduan/reference_genomes/10xgenomics/GRCh38 --fastqs=/home/sduan/data/scrup/fastqs --sample=SRX8778055 --localcores=32 --localmem=128 --output-dir=/home/sduan/data/scrup/alignments/cellranger/SRX8778055 --create-bam true --nosecondary
/home/sduan/software/cellranger/9.0.1/bin/cellranger count --id=SRX8778056 --transcriptome=/home/sduan/reference_genomes/10xgenomics/GRCh38 --fastqs=/home/sduan/data/scrup/fastqs --sample=SRX8778056 --localcores=32 --localmem=128 --output-dir=/home/sduan/data/scrup/alignments/cellranger/SRX8778056 --create-bam true --nosecondary
/home/sduan/software/cellranger/9.0.1/bin/cellranger count --id=SRX8778057 --transcriptome=/home/sduan/reference_genomes/10xgenomics/GRCh38 --fastqs=/home/sduan/data/scrup/fastqs --sample=SRX8778057 --localcores=32 --localmem=128 --output-dir=/home/sduan/data/scrup/alignments/cellranger/SRX8778057 --create-bam true --nosecondary
/home/sduan/software/cellranger/9.0.1/bin/cellranger count --id=SRX8778058 --transcriptome=/home/sduan/reference_genomes/10xgenomics/GRCh38 --fastqs=/home/sduan/data/scrup/fastqs --sample=SRX8778058 --localcores=32 --localmem=128 --output-dir=/home/sduan/data/scrup/alignments/cellranger/SRX8778058 --create-bam true --nosecondary
/home/sduan/software/cellranger/9.0.1/bin/cellranger count --id=SRX8778059 --transcriptome=/home/sduan/reference_genomes/10xgenomics/GRCh38 --fastqs=/home/sduan/data/scrup/fastqs --sample=SRX8778059 --localcores=32 --localmem=128 --output-dir=/home/sduan/data/scrup/alignments/cellranger/SRX8778059 --create-bam true --nosecondary
/home/sduan/software/cellranger/9.0.1/bin/cellranger count --id=SRX8778060 --transcriptome=/home/sduan/reference_genomes/10xgenomics/GRCh38 --fastqs=/home/sduan/data/scrup/fastqs --sample=SRX8778060 --localcores=32 --localmem=128 --output-dir=/home/sduan/data/scrup/alignments/cellranger/SRX8778060 --create-bam true --nosecondary
/home/sduan/software/cellranger/9.0.1/bin/cellranger count --id=SRX8858129 --transcriptome=/home/sduan/reference_genomes/10xgenomics/GRCh38 --fastqs=/home/sduan/data/scrup/fastqs --sample=SRX8858129 --localcores=32 --localmem=128 --output-dir=/home/sduan/data/scrup/alignments/cellranger/SRX8858129 --create-bam true --nosecondary
/home/sduan/software/cellranger/9.0.1/bin/cellranger count --id=SRX8858130 --transcriptome=/home/sduan/reference_genomes/10xgenomics/GRCh38 --fastqs=/home/sduan/data/scrup/fastqs --sample=SRX8858130 --localcores=32 --localmem=128 --output-dir=/home/sduan/data/scrup/alignments/cellranger/SRX8858130 --create-bam true --nosecondary
/home/sduan/software/cellranger/9.0.1/bin/cellranger count --id=SRX8961817 --transcriptome=/home/sduan/reference_genomes/10xgenomics/GRCh38 --fastqs=/home/sduan/data/scrup/fastqs --sample=SRX8961817 --localcores=32 --localmem=128 --output-dir=/home/sduan/data/scrup/alignments/cellranger/SRX8961817 --create-bam true --nosecondary
/home/sduan/software/cellranger/9.0.1/bin/cellranger count --id=SRX8961818 --transcriptome=/home/sduan/reference_genomes/10xgenomics/GRCh38 --fastqs=/home/sduan/data/scrup/fastqs --sample=SRX8961818 --localcores=32 --localmem=128 --output-dir=/home/sduan/data/scrup/alignments/cellranger/SRX8961818 --create-bam true --nosecondary
