#!/usr/bin/env Rscript

suppressPackageStartupMessages({
  library(glue)
  library(jsonlite)
  library(zen4R)
})

`%||%` <- function(x, y) {
  if (is.null(x) || length(x) == 0 || identical(x, "")) {
    y
  } else {
    x
  }
}

parse_bool <- function(x, default = FALSE) {
  if (is.null(x) || length(x) == 0 || identical(x, "")) {
    return(default)
  }
  tolower(x) %in% c("1", "true", "t", "yes", "y")
}

trim_scalar <- function(x) {
  if (length(x) == 0 || is.null(x)) {
    return("")
  }
  trimws(as.character(x[[1]]))
}

null_if_empty <- function(x) {
  value <- trim_scalar(x)
  if (nzchar(value)) value else NULL
}

normalize_path_candidates <- function(paths) {
  unique(normalizePath(paths[file.exists(paths)], mustWork = FALSE))
}

first_existing_path <- function(paths, label) {
  existing <- normalize_path_candidates(paths)
  if (length(existing) == 0) {
    stop(
      glue(
        "Cannot find {label}. Checked: {paste(paths, collapse = ', ')}"
      ),
      call. = FALSE
    )
  }
  existing[[1]]
}

format_size <- function(path) {
  bytes <- file.info(path)$size
  units <- c("B", "KB", "MB", "GB", "TB")
  power <- if (is.na(bytes) || bytes <= 0) {
    1
  } else {
    min(floor(log(bytes, 1024)) + 1, length(units))
  }
  value <- bytes / (1024 ^ (power - 1))
  sprintf("%.2f %s", value, units[[power]])
}

read_json_env <- function(var, default = NULL) {
  value <- Sys.getenv(var, unset = "")
  if (identical(trimws(value), "")) {
    return(default)
  }
  jsonlite::fromJSON(value, simplifyVector = FALSE)
}

coerce_character_vector <- function(x) {
  if (is.null(x) || length(x) == 0) {
    character()
  } else if (is.list(x) && !is.data.frame(x)) {
    unlist(x, use.names = FALSE)
  } else {
    as.character(x)
  }
}

load_config <- function() {
  use_sandbox <- parse_bool(Sys.getenv("ZENODO_USE_SANDBOX", unset = "false"))
  token_env <- if (use_sandbox) "ZENODO_SANDBOX_TOKEN" else "ZENODO_TOKEN"
  token <- Sys.getenv(token_env, unset = "")

  qs_path <- first_existing_path(
    c(
      "data/raw/reference/raw.qs",
      "data/raw/reference/reference.raw.qs"
    ),
    label = "reference qs file"
  )

  bpcells_tar_path <- first_existing_path(
    c(
      "data/raw/reference/bpcells.tar.gz"
    ),
    label = "BPCells archive"
  )

  creators <- read_json_env("ZENODO_CREATORS_JSON", default = list())
  contributors <- read_json_env("ZENODO_CONTRIBUTORS_JSON", default = list())
  related_identifiers <- read_json_env(
    "ZENODO_RELATED_IDENTIFIERS_JSON",
    default = list()
  )

  title <- Sys.getenv(
    "ZENODO_TITLE",
    unset = "immune-atlas reference dataset"
  )
  version <- Sys.getenv(
    "ZENODO_VERSION",
    unset = format(Sys.Date(), "%Y.%m.%d")
  )
  publication_date <- Sys.getenv(
    "ZENODO_PUBLICATION_DATE",
    unset = as.character(Sys.Date())
  )
  description <- Sys.getenv("ZENODO_DESCRIPTION", unset = "")
  if (identical(trimws(description), "")) {
    description <- glue(
      "<p>Reference dataset for the immune-atlas project.</p>
<p>This deposition contains:</p>
<ul>
  <li><code>{basename(qs_path)}</code>: serialized reference object generated by <code>scripts/r/02.building_and_annotating_the_atlas_core/01_build_reference_source_data.R</code>.</li>
  <li><code>{basename(bpcells_tar_path)}</code>: tar.gz archive of the BPCells-backed matrices stored under <code>data/raw/reference/bpcells/</code>.</li>
</ul>
<p>These files are intended to distribute the raw reference resource used to build the immune-atlas reference object and downstream analyses.</p>"
    )
  }

  notes <- Sys.getenv("ZENODO_NOTES", unset = "")
  if (identical(trimws(notes), "")) {
    notes <- glue(
      paste(
        "Files included in this deposition:",
        glue("- {basename(qs_path)} ({format_size(qs_path)})"),
        glue("- {basename(bpcells_tar_path)} ({format_size(bpcells_tar_path)})"),
        "",
        "Provenance:",
        "- Reference object build script: scripts/r/02.building_and_annotating_the_atlas_core/01_build_reference_source_data.R",
        "- Upload script: scripts/r/upload_data.R",
        "",
        "The script defaults to creating or updating a draft deposition.",
        "Publishing is only performed when ZENODO_PUBLISH=true.",
        sep = "\n"
      )
    )
  }

  keywords <- coerce_character_vector(
    read_json_env(
      "ZENODO_KEYWORDS_JSON",
      default = c(
        "immune-atlas",
        "single-cell",
        "reference",
        "Seurat",
        "BPCells",
        "human immune atlas"
      )
    )
  )

  list(
    use_sandbox = use_sandbox,
    token_env = token_env,
    token = token,
    deposition_id = trim_scalar(Sys.getenv("ZENODO_DEPOSITION_ID", unset = "")),
    publish = parse_bool(Sys.getenv("ZENODO_PUBLISH", unset = "false")),
    overwrite_files = parse_bool(Sys.getenv("ZENODO_OVERWRITE_FILES", unset = "true")),
    title = title,
    version = version,
    publication_date = publication_date,
    description = description,
    notes = notes,
    upload_type = trim_scalar(Sys.getenv("ZENODO_UPLOAD_TYPE", unset = "dataset")),
    language = trim_scalar(Sys.getenv("ZENODO_LANGUAGE", unset = "eng")),
    access_right = trim_scalar(Sys.getenv("ZENODO_ACCESS_RIGHT", unset = "public")),
    license = trim_scalar(Sys.getenv("ZENODO_LICENSE", unset = "cc-by-4.0")),
    keywords = keywords,
    creators = creators,
    contributors = contributors,
    related_identifiers = related_identifiers,
    files = c(qs_path, bpcells_tar_path)
  )
}

validate_config <- function(config) {
  if (identical(trimws(config$token), "")) {
    stop(
      glue("Missing Zenodo access token in environment variable `{config$token_env}`."),
      call. = FALSE
    )
  }

  if (length(config$creators) == 0) {
    stop(
      paste(
        "Missing creators.",
        "Set `ZENODO_CREATORS_JSON` to a JSON array, for example:",
        "[{\"firstname\":\"YourGivenName\",\"lastname\":\"YourFamilyName\",\"affiliations\":[\"Your Institute\"],\"orcid\":\"0000-0000-0000-0000\"}]"
      ),
      call. = FALSE
    )
  }

  missing_files <- config$files[!file.exists(config$files)]
  if (length(missing_files) > 0) {
    stop(
      glue("Missing upload files: {paste(missing_files, collapse = ', ')}"),
      call. = FALSE
    )
  }

  invisible(config)
}

add_people <- function(record, people, mode = c("creator", "contributor"), sandbox = FALSE) {
  mode <- match.arg(mode)
  if (length(people) == 0) {
    return(invisible(record))
  }

  for (person in people) {
    firstname <- trim_scalar(person$firstname %||% "")
    lastname <- trim_scalar(person$lastname %||% "")
    name <- trim_scalar(person$name %||% "")

    affiliations <- coerce_character_vector(person$affiliations %||% character())
    affiliations <- affiliations[nzchar(affiliations)]

    common_args <- list(
      firstname = if (nzchar(firstname)) firstname else NULL,
      lastname = if (nzchar(lastname)) lastname else NULL,
      name = if (nzchar(name)) name else NULL,
      orcid = null_if_empty(person$orcid %||% ""),
      gnd = null_if_empty(person$gnd %||% ""),
      isni = null_if_empty(person$isni %||% ""),
      ror = null_if_empty(person$ror %||% ""),
      affiliations = if (length(affiliations) > 0) affiliations else NULL,
      sandbox = sandbox
    )

    common_args <- common_args[!vapply(common_args, is.null, logical(1))]

    if (identical(mode, "creator")) {
      do.call(record$addCreator, common_args)
    } else {
      contributor_args <- common_args
      role <- trim_scalar(person$role %||% "")
      if (nzchar(role)) {
        contributor_args$role <- role
      }
      do.call(record$addContributor, contributor_args)
    }
  }

  invisible(record)
}

add_related_identifiers <- function(record, related_identifiers) {
  if (length(related_identifiers) == 0) {
    return(invisible(record))
  }

  for (item in related_identifiers) {
    identifier <- trim_scalar(item$identifier %||% "")
    scheme <- trim_scalar(item$scheme %||% "")
    relation_type <- trim_scalar(item$relation_type %||% "")
    resource_type <- trim_scalar(item$resource_type %||% "")

    if (!nzchar(identifier) || !nzchar(scheme) || !nzchar(relation_type)) {
      stop(
        paste(
          "Each related identifier entry must define",
          "`identifier`, `scheme`, and `relation_type`."
        ),
        call. = FALSE
      )
    }

    record$addRelatedIdentifier(
      identifier = identifier,
      scheme = scheme,
      relation_type = relation_type,
      resource_type = if (nzchar(resource_type)) resource_type else NULL
    )
  }

  invisible(record)
}

configure_record <- function(record, config) {
  record$setTitle(config$title)
  record$setDescription(config$description)
  record$setVersion(config$version)
  record$setPublicationDate(config$publication_date)
  record$setUploadType(config$upload_type)
  record$setAccessPolicyRecord(config$access_right)
  record$setLicense(config$license, sandbox = config$use_sandbox)
  record$setLanguage(config$language)

  if (length(config$keywords) > 0) {
    record$setKeywords(config$keywords)
  }
  if (nzchar(config$notes)) {
    record$setNotes(config$notes)
  }

  record$metadata$creators <- list()
  record$metadata$contributors <- list()
  record$metadata$related_identifiers <- list()

  add_people(
    record = record,
    people = config$creators,
    mode = "creator",
    sandbox = config$use_sandbox
  )
  add_people(
    record = record,
    people = config$contributors,
    mode = "contributor",
    sandbox = config$use_sandbox
  )
  add_related_identifiers(
    record = record,
    related_identifiers = config$related_identifiers
  )

  invisible(record)
}

upsert_draft_record <- function(zenodo, config) {
  if (nzchar(config$deposition_id)) {
    message(glue("Using existing deposition draft: {config$deposition_id}"))
    record <- zenodo$getDepositionById(config$deposition_id)
  } else {
    message("Creating a new Zenodo draft deposition")
    record <- zen4R::ZenodoRecord$new()
  }

  configure_record(record, config)

  zenodo$depositRecord(
    record = record,
    reserveDOI = TRUE,
    publish = FALSE
  )
}

upload_files <- function(zenodo, record, files, overwrite = TRUE) {
  existing_files <- zenodo$getFiles(record$id)
  existing_names <- vapply(existing_files, function(x) x$filename, character(1))

  for (path in files) {
    filename <- basename(path)
    if (overwrite && filename %in% existing_names) {
      message(glue("Deleting existing remote file before re-upload: {filename}"))
      zenodo$deleteFile(record$id, filename)
    }
    message(glue("Uploading {filename}"))
    zenodo$uploadFile(path, record = record)
  }

  invisible(record)
}

print_plan <- function(config, execute = FALSE) {
  cat("Zenodo upload configuration\n")
  cat("===========================\n")
  cat(glue("Mode: {if (execute) 'execute' else 'dry-run'}\n"))
  cat(glue("Sandbox: {config$use_sandbox}\n"))
  cat(glue("Token env: {config$token_env}\n"))
  cat(glue("Existing deposition id: {if (nzchar(config$deposition_id)) config$deposition_id else '<new draft>'}\n"))
  cat(glue("Publish after upload: {config$publish}\n"))
  cat(glue("Title: {config$title}\n"))
  cat(glue("Version: {config$version}\n"))
  cat(glue("Publication date: {config$publication_date}\n"))
  cat(glue("Upload type: {config$upload_type}\n"))
  cat(glue("License: {config$license}\n"))
  cat(glue("Access right: {config$access_right}\n"))
  cat(glue("Creators configured: {length(config$creators)}\n"))
  cat(glue("Contributors configured: {length(config$contributors)}\n"))
  cat(glue("Related identifiers configured: {length(config$related_identifiers)}\n"))
  cat("Files:\n")
  for (path in config$files) {
    cat(glue("  - {path} ({format_size(path)})\n"))
  }
  cat("\n")
}

upload_reference_to_zenodo <- function(config, execute = FALSE) {
  validate_config(config)
  print_plan(config, execute = execute)

  if (!isTRUE(execute)) {
    message(
      paste(
        "Dry-run only. No network request was made.",
        "Re-run with `Rscript scripts/r/upload_data.R --execute` to create/update the draft."
      )
    )
    return(invisible(config))
  }

  zenodo <- zen4R::ZenodoManager$new(
    token = config$token,
    sandbox = config$use_sandbox,
    logger = "INFO"
  )

  record <- upsert_draft_record(zenodo, config)
  upload_files(
    zenodo = zenodo,
    record = record,
    files = config$files,
    overwrite = config$overwrite_files
  )

  if (isTRUE(config$publish)) {
    message(glue("Publishing deposition {record$id}"))
    zenodo$publishRecord(record$id)
  } else {
    message(glue("Draft deposition ready: {record$id}"))
    if (!is.null(record$links$html)) {
      message(glue("Draft URL: {record$links$html}"))
    }
  }

  invisible(record)
}

main <- function() {
  args <- commandArgs(trailingOnly = TRUE)
  execute <- "--execute" %in% args

  config <- load_config()
  upload_reference_to_zenodo(config, execute = execute)
}

if (sys.nframe() == 0) {
  main()
}
